---
global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-autodesk-forge
  s3bucket: autodesk-forge-cloudformation
  #s3bucket: taskcat-sample-taskcat-project-a1c14bc9
  regions:
    - us-east-2
  reporting: true
tests:
  taskcat-json:
    parameter_input: forge-qs-inputs.json
    regions:
      - us-east-2
    template_file: autodeskforge-quickstart-json-master.template