---
global:
  owner: quickstart-eng@amazon.com
  qsname: quickstart-autodesk-forge
  s3bucket: autodesk-forge-cfqs
  #s3bucket: taskcat-sample-taskcat-project-a1c14bc9
  regions:
    - eu-west-1
  reporting: true
tests:
  taskcat-json:
    parameter_input: forge-qs-inputs.json
    regions:
      - eu-west-1
    template_file: autodesk-forge-master.json